export const ghosts =  [
    {
        id: 1,
        name: 'Skater Ghost',
        img: 'skater-ghost.png',
        description: 'Do you want to go fast? This rad boy can take you for a ride.',
        category: `skill`,
        price: '4 skateboard wheels',
    },
    {
        id: 2,
        name: 'Pizza Ghost',
        img: 'pizza-ghost.png',
        description: `Pizza Ghost makes sure your turtle's favorite snack is always on hand.`,
        category: `food`,
        price: `8 discarded crusts`,
    },
    {
        id: 3,
        name: 'Opossum Ghost',
        img: 'opossum-ghost.png',
        description: `Have you ever needed to get out of a situation by playing dead? Well, Opossum Ghost will help you play the deadest of dead and keep you safe.`,
        category: `care`,
        price: '10 worms',
    },
    {
        id: 4,
        name: 'Off Beat Ghost',
        img: 'off-beat-ghost.png',
        description: 'Off Beat Ghost will ruin every song your enemy ever wants to listen to. The perfect revenge companion.',
        category: `skill`,
        price: '3 vintage records',
    },
    {
        id: 5,
        name: 'Fruit Ghost',
        img: 'fruit-ghost.png',
        description: 'This total sweetheart of a ghost knows all the seasonal fruits and where to find them and makes sure you know too.',
        category: `food`,
        price: 'A handful of boysenberries',
    },
    {
        id: 6,
        name: 'Plant Ghost',
        img: 'plant-ghost.png',
        description: 'Is your home a graveyard for house plants? This ghost cares for spirits of all the plants you have killed.',
        category: `skill`,
        price: '7 leaves',
    },
    {
        id: 7,
        name: 'Bad Photo Ghost',
        img: 'bad-photo-ghost.png',
        description: `Bad Photo Ghost knows all your best angles, and they artistically blur you in every photo you look bad in.`,
        category: `care`,
        price: '15 rolls of film',
    },
    {
        id: 8,
        name: 'Water Ghost',
        img: 'water-ghost.png',
        description: 'Do you ever need to breath underwater? Water Ghost is the very air you need where there is none. They are here for you for any spontaneous diving sessions. *does not supply air in outer space*',
        category: `skill`,
        price: '1 bottle of rose water',
    },
    {
        id: 9,
        name: 'Human Ghost',
        img: 'human-ghost.png',
        description: `Wrap your lonely heart in the tender embrace of Human Ghost.`,
        category: `care`,
        price: '1 bottle of rose water',
    },
]